### ISSUE TITLE
Compatibility with Ansible 2.13 and above

### ISSUE THREAD

**Issue by camrossi** [noironetworks/openshift_vsphere_upi#14]
Due to a change in behaviour in how [Templating](https://docs.ansible.com/ansible-core/devel/porting_guides/porting_guide_core_2.13.html#playbook) works in ansible 2.13+ the generation of `masters_api_ip_list` and `workers_api_ip_list` will fail in the [common](https://github.com/noironetworks/openshift_vsphere_upi/blob/master/roles/common/tasks/main.yml#L116) role.

Our code can be re-written as:
```
- set_fact:
      masters_api_ip_list: "{{ masters_api_ip_list | default([]) + [ item.value.ip ] }}"
  with_dict: "{{ masters_vars.nodes }}"

- set_fact:
     workers_api_ip_list: "{{ workers_api_ip_list | default([]) + [ item.value.ip ] }}"
  with_dict: "{{ workers_vars.nodes }}"
```
